version: "2"

run:
  timeout: 2m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - gocritic
    - bodyclose
    - noctx
    - revive
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    disable:
      - fieldalignment
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
        arguments: [disableStutterCheck]
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: duplicated-imports
      - name: modifies-value-receiver

issues:
  exclude-use-default: false
