package pgcontract

// Fast-tier unit tests for the PURE merge-key derivation (MergeKeyColumns):
// every case runs on hand-built catalog facts with no database, so DI-3's
// rule is pinned without Postgres. A single-column NOT NULL UNIQUE
// constraint is an acceptable merge key for a keyless table only when the
// producer can supply its value: any database-generated candidate
// (sequence-backed, identity, or GENERATED ALWAYS) is excluded, never
// merely deprioritized. Two or more equally valid supplyable candidates
// refuse, rather than pick one by input order.

import (
	"errors"
	"strings"
	"testing"

	"github.com/JacobJNilsson/data-contract-generator/odcs"
	"github.com/JacobJNilsson/data-contract-generator/pgintrospect"
)

// identityColumn builds a Column carrying the identity surrogate signal: a
// NOT NULL, single-column UNIQUE, database-assigned value. Postgres reports
// the same is_identity = "YES" fact whether the column is declared
// GENERATED ALWAYS AS IDENTITY or GENERATED BY DEFAULT AS IDENTITY; the
// catalog read this package works from does not keep the two forms apart.
func identityColumn(table, name string) pgintrospect.Column {
	c := col(table, name, "uuid", "NO")
	c.IsIdentity = "YES"
	return c
}

// naturalColumn builds a Column carrying no surrogate signal: a NOT NULL
// column whose value the producer supplies, whatever its Postgres type. A
// uuid column defaulting to a plain gen_random_uuid() call (the trial's
// category.eid) has this exact shape: HasDefault is true, but none of the
// three database-generated signals are set, so the producer may still
// supply its own value.
func naturalColumn(table, name, dataType string) pgintrospect.Column {
	return col(table, name, dataType, "NO")
}

// generatedAlwaysColumn builds a Column carrying ONLY the IsGenerated
// surrogate signal (never IsIdentity or IsSequenceDefault): a GENERATED
// ALWAYS column, the shape a computed or stored-generated column carries.
func generatedAlwaysColumn(table, name, dataType string) pgintrospect.Column {
	c := col(table, name, dataType, "NO")
	c.IsGenerated = "ALWAYS"
	return c
}

// sequenceColumn builds a Column carrying ONLY the IsSequenceDefault
// surrogate signal (never IsIdentity or IsGenerated): a SERIAL/BIGSERIAL
// column whose default is a nextval(...) call.
func sequenceColumn(table, name, dataType string) pgintrospect.Column {
	c := col(table, name, dataType, "NO")
	c.IsSequenceDefault = true
	return c
}

func uc(name string, columns ...string) odcs.UniqueConstraint {
	return odcs.UniqueConstraint{Name: name, Columns: columns}
}

// wantKeyRefusal asserts that err is a *KeyRefusalError naming wantTable,
// wrapping wantKind (so both errors.As and errors.Is work for a caller),
// and whose message contains wantSubstr.
func wantKeyRefusal(t *testing.T, err error, wantTable string, wantKind error, wantSubstr string) {
	t.Helper()
	if err == nil {
		t.Fatal("error = nil, want a refusal")
	}
	var keyErr *KeyRefusalError
	if !errors.As(err, &keyErr) {
		t.Fatalf("error = %v, want it to be a *KeyRefusalError", err)
	}
	if keyErr.Table != wantTable {
		t.Errorf("KeyRefusalError.Table = %q, want %q", keyErr.Table, wantTable)
	}
	if !errors.Is(err, wantKind) {
		t.Errorf("errors.Is(err, %v) = false, want true", wantKind)
	}
	if !strings.Contains(err.Error(), wantSubstr) {
		t.Errorf("error = %q, want it to contain %q", err.Error(), wantSubstr)
	}
}

// TestMergeKeyColumnsKeylessPlainDefaultUUIDIsAcceptable pins the trial case
// (DI-3, refined): category has no primary key, and its only single-column
// NOT NULL UNIQUE constraint is on eid, a uuid column with a PLAIN default
// (gen_random_uuid()) — no database-generated signal at all. The producer
// can supply the value, so it is the merge key.
func TestMergeKeyColumnsKeylessPlainDefaultUUIDIsAcceptable(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"eid": naturalColumn("category", "eid", "uuid"),
	}
	got, err := MergeKeyColumns("category", nil, []odcs.UniqueConstraint{uc("category_eid_key", "eid")}, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "eid" {
		t.Errorf("MergeKeyColumns() = %v, want [eid]", got)
	}
}

// TestMergeKeyColumnsKeylessPrefersSupplyableAmongCandidates pins the
// exclusion, not mere deprioritization, of a database-generated candidate:
// when a keyless table carries both a supplyable and an identity-backed
// single-column NOT NULL UNIQUE constraint, the identity one never competes
// at all, so the supplyable one wins as the SOLE remaining candidate.
func TestMergeKeyColumnsKeylessPrefersSupplyableAmongCandidates(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"code": naturalColumn("widget", "code", "text"),
		"eid":  identityColumn("widget", "eid"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("widget_eid_key", "eid"),
		uc("widget_code_key", "code"),
	}
	got, err := MergeKeyColumns("widget", nil, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "code" {
		t.Errorf("MergeKeyColumns() = %v, want [code] (the identity column is excluded, not merely deprioritized)", got)
	}
}

// TestMergeKeyColumnsKeylessNoCandidateRefuses pins the still-refused case: a
// keyless table with no supplyable single-column NOT NULL UNIQUE constraint
// has no faithful merge key, whether because a unique constraint is
// nullable, multi-column, sequence-backed, or simply absent. It also pins
// the typed refusal surface: errors.As recovers a *KeyRefusalError naming
// the table, and errors.Is matches ErrNoMergeKeyCandidate.
func TestMergeKeyColumnsKeylessNoCandidateRefuses(t *testing.T) {
	cases := []struct {
		name    string
		uniques []odcs.UniqueConstraint
		facts   map[string]pgintrospect.Column
	}{
		{name: "no unique constraints at all"},
		{
			name:    "single-column unique but nullable",
			uniques: []odcs.UniqueConstraint{uc("t_col_key", "col")},
			facts:   map[string]pgintrospect.Column{"col": col("t", "col", "uuid", "YES")},
		},
		{
			name:    "only a multi-column unique constraint",
			uniques: []odcs.UniqueConstraint{uc("t_ab_key", "a", "b")},
			facts: map[string]pgintrospect.Column{
				"a": naturalColumn("t", "a", "text"),
				"b": naturalColumn("t", "b", "text"),
			},
		},
		{
			name:    "an empty-column unique entry is skipped, not a candidate",
			uniques: []odcs.UniqueConstraint{uc("t_empty_key")},
		},
		{
			// A bigserial-only table has no producer-supplyable value at
			// all, so the sole candidate is excluded, never used as a
			// fallback. The keyless table refuses instead of keying on it.
			name:    "only a sequence-backed serial unique column",
			uniques: []odcs.UniqueConstraint{uc("t_id_key", "id")},
			facts:   map[string]pgintrospect.Column{"id": sequenceColumn("t", "id", "bigint")},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := MergeKeyColumns("t", nil, tc.uniques, tc.facts)
			if err == nil {
				t.Fatalf("MergeKeyColumns() = %v, nil error, want a refusal", got)
			}
			wantKeyRefusal(t, err, "t", ErrNoMergeKeyCandidate,
				`table "t" declares no merge key (no primary key, and no single-column NOT NULL UNIQUE constraint to merge on)`)
		})
	}
}

// TestMergeKeyColumnsKeylessGeneratedAlwaysIdentityRefuses pins the exact
// finding this refinement fixes: eid integer GENERATED ALWAYS AS IDENTITY
// NOT NULL UNIQUE on a keyless table. The producer can never supply an
// identity value, so every re-delivery would insert a duplicate; the
// derivation must refuse rather than accept it as a fallback merge key.
func TestMergeKeyColumnsKeylessGeneratedAlwaysIdentityRefuses(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"eid": identityColumn("widget", "eid"),
	}
	uniques := []odcs.UniqueConstraint{uc("widget_eid_key", "eid")}
	got, err := MergeKeyColumns("widget", nil, uniques, facts)
	if err == nil {
		t.Fatalf("MergeKeyColumns() = %v, nil error, want a refusal", got)
	}
	wantKeyRefusal(t, err, "widget", ErrNoMergeKeyCandidate,
		`table "widget" declares no merge key`)
}

// TestMergeKeyColumnsKeylessIdentityByDefaultRefuses pins the same refusal
// for the OTHER identity DDL form: GENERATED BY DEFAULT AS IDENTITY. The
// catalog read reports the identical is_identity = "YES" fact for both
// forms (see identityColumn's doc), so both must refuse the same way — a
// database-assigned identity value is never supplyable, regardless of which
// DDL produced it.
func TestMergeKeyColumnsKeylessIdentityByDefaultRefuses(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"eid": identityColumn("widget", "eid"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("widget_id_key", "id"), // a sequence-backed candidate, also excluded
		uc("widget_eid_key", "eid"),
	}
	facts["id"] = sequenceColumn("widget", "id", "bigint")
	got, err := MergeKeyColumns("widget", nil, uniques, facts)
	if err == nil {
		t.Fatalf("MergeKeyColumns() = %v, nil error, want a refusal", got)
	}
	wantKeyRefusal(t, err, "widget", ErrNoMergeKeyCandidate,
		`table "widget" declares no merge key`)
}

// TestMergeKeyColumnsKeylessMultipleNaturalCandidatesRefuses pins the DI-3
// refinement: two equally valid supplyable single-column NOT NULL UNIQUE
// candidates on a keyless table are a refusal, never an alphabetical-order
// pick. It also pins the typed refusal surface for the ambiguous case:
// errors.Is matches ErrAmbiguousMergeKeyCandidates.
func TestMergeKeyColumnsKeylessMultipleNaturalCandidatesRefuses(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"email": naturalColumn("t", "email", "text"),
		"phone": naturalColumn("t", "phone", "text"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("t_email_key", "email"),
		uc("t_phone_key", "phone"),
	}
	got, err := MergeKeyColumns("t", nil, uniques, facts)
	if err == nil {
		t.Fatalf("MergeKeyColumns() = %v, nil error, want a refusal", got)
	}
	wantKeyRefusal(t, err, "t", ErrAmbiguousMergeKeyCandidates,
		`table "t" has 2 equally valid merge key candidates`)
}

// TestMergeKeyColumnsKeylessAmbiguityCountsOnlySupplyableCandidates pins the
// refined ambiguity count: a keyless table carrying two tied supplyable
// candidates AND an identity-backed candidate still refuses on exactly 2,
// not 3 — the excluded identity candidate never enters the count, and never
// appears in the refusal's candidate list.
func TestMergeKeyColumnsKeylessAmbiguityCountsOnlySupplyableCandidates(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"email": naturalColumn("t", "email", "text"),
		"phone": naturalColumn("t", "phone", "text"),
		"eid":   identityColumn("t", "eid"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("t_email_key", "email"),
		uc("t_phone_key", "phone"),
		uc("t_eid_key", "eid"),
	}
	got, err := MergeKeyColumns("t", nil, uniques, facts)
	if err == nil {
		t.Fatalf("MergeKeyColumns() = %v, nil error, want a refusal", got)
	}
	wantKeyRefusal(t, err, "t", ErrAmbiguousMergeKeyCandidates,
		`table "t" has 2 equally valid merge key candidates (email, phone)`)
	if strings.Contains(err.Error(), "eid") {
		t.Errorf("error = %q, must not name the excluded identity candidate eid", err.Error())
	}
}

// TestMergeKeyColumnsCompositePrimaryKeyIsKept: a multi-column primary key is
// a deliberate compound identity and is never overridden.
func TestMergeKeyColumnsCompositePrimaryKeyIsKept(t *testing.T) {
	pk := []string{"tenant_id", "id"}
	got, err := MergeKeyColumns("t", pk, nil, nil)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 2 || got[0] != "tenant_id" || got[1] != "id" {
		t.Errorf("MergeKeyColumns() = %v, want %v", got, pk)
	}
}

// TestMergeKeyColumnsNonSurrogatePrimaryKeyIsKept: a single-column primary
// key that is not a surrogate already IS the meaningful merge key.
func TestMergeKeyColumnsNonSurrogatePrimaryKeyIsKept(t *testing.T) {
	facts := map[string]pgintrospect.Column{"code": naturalColumn("t", "code", "text")}
	got, err := MergeKeyColumns("t", []string{"code"}, nil, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "code" {
		t.Errorf("MergeKeyColumns() = %v, want [code]", got)
	}
}

// TestMergeKeyColumnsSurrogatePrimaryKeyOverriddenByNarrowestBusinessKey: a
// single-column surrogate primary key is overridden by the narrowest UNIQUE
// constraint that touches no surrogate column. It also carries an
// empty-column unique entry, defensively skipped rather than treated as a
// zero-width candidate.
func TestMergeKeyColumnsSurrogatePrimaryKeyOverriddenByNarrowestBusinessKey(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"id":      identityColumn("t", "id"),
		"account": naturalColumn("t", "account", "text"),
		"date":    naturalColumn("t", "date", "date"),
		"sku":     naturalColumn("t", "sku", "text"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("t_empty_key"),
		uc("t_account_date_key", "account", "date"),
		uc("t_sku_key", "sku"),
	}
	got, err := MergeKeyColumns("t", []string{"id"}, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "sku" {
		t.Errorf("MergeKeyColumns() = %v, want [sku] (narrowest non-surrogate candidate)", got)
	}
}

// TestMergeKeyColumnsGeneratedAlwaysPrimaryKeyOverridden: a single-column
// primary key flagged ONLY through IsGenerated ("ALWAYS"), never IsIdentity
// or IsSequenceDefault, is still a surrogate and is still overridden. This
// pins the IsGenerated branch of isSurrogateColumn on its own, independent
// of IsIdentity.
func TestMergeKeyColumnsGeneratedAlwaysPrimaryKeyOverridden(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"id":  generatedAlwaysColumn("t", "id", "bigint"),
		"sku": naturalColumn("t", "sku", "text"),
	}
	uniques := []odcs.UniqueConstraint{uc("t_sku_key", "sku")}
	got, err := MergeKeyColumns("t", []string{"id"}, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "sku" {
		t.Errorf("MergeKeyColumns() = %v, want [sku] (GENERATED ALWAYS primary key overridden)", got)
	}
}

// TestMergeKeyColumnsSequenceDefaultPrimaryKeyOverridden: a single-column
// primary key flagged ONLY through IsSequenceDefault, never IsIdentity or
// IsGenerated, is still a surrogate and is still overridden. This pins the
// IsSequenceDefault branch of isSurrogateColumn on its own, the shape a
// SERIAL/BIGSERIAL primary key carries.
func TestMergeKeyColumnsSequenceDefaultPrimaryKeyOverridden(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"id":  sequenceColumn("t", "id", "integer"),
		"sku": naturalColumn("t", "sku", "text"),
	}
	uniques := []odcs.UniqueConstraint{uc("t_sku_key", "sku")}
	got, err := MergeKeyColumns("t", []string{"id"}, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "sku" {
		t.Errorf("MergeKeyColumns() = %v, want [sku] (SERIAL/BIGSERIAL primary key overridden)", got)
	}
}

// TestMergeKeyColumnsSurrogatePrimaryKeyKeptOnTie: two equally narrow
// non-surrogate candidates leave the choice ambiguous, so the derivation
// fails closed and keeps the surrogate primary key rather than guessing.
func TestMergeKeyColumnsSurrogatePrimaryKeyKeptOnTie(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"id":    identityColumn("t", "id"),
		"email": naturalColumn("t", "email", "text"),
		"phone": naturalColumn("t", "phone", "text"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("t_email_key", "email"),
		uc("t_phone_key", "phone"),
	}
	got, err := MergeKeyColumns("t", []string{"id"}, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "id" {
		t.Errorf("MergeKeyColumns() = %v, want [id] (tie falls back to the primary key)", got)
	}
}

// TestMergeKeyColumnsSurrogatePrimaryKeyKeptWhenNoBusinessCandidate: with no
// non-surrogate UNIQUE constraint to override with (either none at all, or
// every one touches a surrogate column), the surrogate primary key is kept.
func TestMergeKeyColumnsSurrogatePrimaryKeyKeptWhenNoBusinessCandidate(t *testing.T) {
	facts := map[string]pgintrospect.Column{
		"id":      identityColumn("t", "id"),
		"ext":     identityColumn("t", "ext"),
		"account": naturalColumn("t", "account", "text"),
	}
	uniques := []odcs.UniqueConstraint{
		uc("t_ext_account_key", "ext", "account"), // touches the surrogate "ext"
	}
	got, err := MergeKeyColumns("t", []string{"id"}, uniques, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "id" {
		t.Errorf("MergeKeyColumns() = %v, want [id] (no non-surrogate candidate)", got)
	}

	got, err = MergeKeyColumns("t", []string{"id"}, nil, facts)
	if err != nil {
		t.Fatalf("MergeKeyColumns() error = %v, want nil", err)
	}
	if len(got) != 1 || got[0] != "id" {
		t.Errorf("MergeKeyColumns() = %v, want [id] (no unique constraints at all)", got)
	}
}
